#!/bin/bash
sleep 1
exec 2>&1
while true; do sleep 1; /sbin/route del -net default metric 5 dev ppp0; /sbin/route add -net default metric 5 dev ppp0 && break; done
sysctl net.ipv4.ip_forward=1
iptables -t nat -A POSTROUTING -o ppp0 -j MASQUERADE
exec cat
